server:
  port: ${APP_PORT}
spring:
  application:
    name: Ecommerce
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

  # send-mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # google
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: ${FACEBOOK_REDIRECT_URI}
            auth-uri: https://www.facebook.com/v21.0/dialog/oauth
            token-uri: https://graph.facebook.com/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.type(large)
  # file
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: ${API_PREFIX}

# swagger-ui
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

# jwt
jwt:
  expiration: ${JWT_EXPIRATION}
  refreshExpiration: ${JWT_REFRESH_EXPIRATION}
  secretKey: ${JWT_SECRET_KEY}

# payment
payment:
  vnPay:
    url: ${PAYMENT_URL}
    tmnCode: ${PAYMENT_TMN_CODE}
    secretKey: ${PAYMENT_SECRET_KEY}
    returnUrl: ${PAYMENT_RETURN_URL}
    version: 2.1.0
    command: pay
    orderType: other

# cloudinary
cloudinary:
  cloudName: ${CLOUDINARY_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret: ${CLOUDINARY_API_SECRET}

# Health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: ${HEALTH_CHECK_BASE_PATH}
      exposure:
        #include: "health"
        include: "health, info"